################################# Default configuration ###################
baseURL = "https://essucalgary.netlify.com"
title = "Engineering Students' Society U of C"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "About"
  name = "Constitution"
  URL = "about/constitution"

  [[menu.main]]
  parent = "About"
  name = "Council"
  URL = "about/council"

  [[menu.main]]
  parent = "About"
  name = "Departments"
  URL = "departments"

  [[menu.main]]
  parent = "About"
  name = "Sponsors"
  URL = "sponsors"

[[menu.main]]
name = "Events"
URL = "events"
weight = 2

[[menu.main]]
name = "Services"
weight = 3
hasChildren = true

  [[menu.main]]
  parent = "Services"
  name = "Bookings"
  URL = "bookings"

  [[menu.main]]
  parent = "Services"
  name = "Resources"
  URL = "Resources"

[[menu.main]]
name = "Get Involved"
weight = 4
hasChildren = true

  [[menu.main]]
  parent = "Get Involved"
  name = "Projects Hub"
  URL = "projects-Hub"

  [[menu.main]]
  parent = "Get Involved"
  name = "Volunteer Hub"
  URL = "volunteer-Hub"

  [[menu.main]]
  parent = "Get Involved"
  name = "Applications"
  URL = "get-involved/applications"

  [[menu.main]]
  parent = "Get Involved"
  name = "Confrences"
  URL = "confrences"

  [[menu.main]]
  parent = "Get Involved"
  name = "Teams"
  URL = "teams"
  
[[menu.main]]
name = "Contact us"
URL = "contact"
weight = 5

[[menu.main]]
name = "Store"
URL = "https://ess-test.square.site/"
weight = 6


# footer menu
[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 1

[[menu.footer]]
name = "Office Hours"
URL = "hours"
weight = 2

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Engineering Students' Society University of Calgary"
# Contact Information
mobile = "0124857985320"
email = "president@essu.calgary.ca"
location = "North Main Street,Brooklyn Australia"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# booking form action
booking_form_action = "https://formspree.io/mzbjbvzo"
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


############################# social site ########################
[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/ess_uofc/"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/company/engineering-students%27-society-u-of-c-/"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/UofC.ESS"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/ESS_UofC"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Engineering Students Society University of Calgary. All Rights Reserved"

################################ France Language ########################
# [Languages.fr]
# languageName = "Fr"
# languageCode = "fr-fr"
# contentDir = "content/french"
# weight = 2
# home = "Accueil"
# # copyright
# copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
