backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
logo_url: https://essucalgary.com/images/ess-logo.png
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/english/news" # The path to the folder where the documents are stored
    filter: {field: "is_index", value: false}
    editor:
      preview: false # disable preview view
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Index File", name: "is_index", widget: "hidden", default: "false"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Background Image", name: bg_image", widget: "image"}
      - {label: "Author", name: "author", widget: "string", default: "ESS"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["News"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "diversity" # Used in routes, e.g., /admin/collections/blog
    label: "Diversity" # Used in the UI
    folder: "content/english/diversity" # The path to the folder where the documents are stored
    editor:
      preview: false # disable preview view
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "DAC Post", name: "dacpost", widget: "hidden", default: true}
      - {label: "Additional Resources", name: "additional_resources", widget: "hidden", default: {enable: false}}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "PublishDate", widget: "datetime"}
      - {label: "Post Image", name: "post_image", widget: "image"}
      - {label: "Author", name: "author", widget: "string" }
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "council"
    label: "Council Members"
    folder: "content/english/about/members"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Member Type", name: "memberType", widget: "select", options: ["commissioner", "executive", "firstyearrep", "director"]}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Pronouns", name: "pronouns", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Profile Image", name: "image", widget: "image"}
      - {label: "Bio", name: "body", widget: "markdown"}
  - name: "team"
    label: "Teams"
    folder: "content/english/get-involved/teams"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Team Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Header Image", name: "bg_image", widget: "image", default: "/images/about/202021-group-council-1-banner.jpg"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - label: "President Information"
        name: "president"
        widget: object
        collapsed: false
        fields:
          - {label: "Name(s)", name: "name", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "President(s) Image", name: "bio_img", widget: "image"}
          - {label: "Email", name: "email", widget: "string"}
      - label: "Social Media"
        name: "social"
        widget: object
        collapsed: false
        fields:
          - {label: "Website", name: "website", widget: "string"}
          - {label: "Facebook", name: "facebook", widget: "string"}
          - {label: "Twitter", name: "twitter", widget: "string"}
          - {label: "Instagram", name: "instagran", widget: "string"}
          - {label: "Linkedin", name: "linkedin", widget: "string"}
          - {label: "YouTube", name: "youtube", widget: "string"}
      - {label: "Club Information", name: "body", widget: "markdown"}
  - name: "applications"
    label: "Applications"
    folder: "content/english/get-involved/applications"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Application Title", name: "title", widget: "string"}
      - {label: "Application Subtitle", name: "description", widget: "string"}
      - {label: "Header Image", name: "bg_image", widget: "image"}
      - {label: "Main Image", name: "content_image", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "posting"}
      - {label: "Currently Accepting", name: "accepting", widget: boolean}
      - {label: "Role Title", name: "role", widget: "string"}
      - {label: "Application Tags", name: "job_tags", widget: "list", allow_add: true}
      - {label: "PDF Application Link", name: "application_pdf_link", widget: "string"}
      - {label: "Ending Date", name: "ending_date", widget: date}
      - {label: "Posting Body", name: "body", widget: "markdown"}