---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/english/covid-19.md
  label: COVID-19
- type: directory
  path: content/english
  label: Content
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: About
- type: document
  path: content/english/about/constitution.md
  label: Constitution
- type: directory
  path: content/english/about/departments
  label: Departments
  create: all
  match: "**/*"
  new_doc_ext: app
  templates:
  - department
- type: directory
  path: content/english/about/sponsors
  label: Sponsors
  create: all
  match: "**/*"
  templates:
  - sponsor
- type: document
  path: content/english/about/officehours/_index.md
  label: Office Hours
- type: heading
  label: Events
- type: directory
  path: content/english/events
  label: Events
  create: all
  match: "**/*"
- type: heading
  label: Services
- type: heading
  label: Get Involved
- type: document
  path: content/english/bookings/_index.md
  label: Bookings
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
